

export const links = [
  {
    name: "Dashboard",
    href: "/",
    icon: "/home.svg",
    icon2: "/home-2.svg",
  },
  {
    name: "Users",
    href: "/users",
    icon: "/medal-star.svg",
    icon2: "/medal-star-2.svg",
  },
  {
    name: "Listings",
    href: "/listings",
    icon: "/location.svg",
    icon2: "/location-2.svg",
  },
  {
    name: "Bookings",
    href: "/bookings",
    icon: "/bookings.svg",
    icon2: "/bookings-2.svg",
  },
  {
    name: "Revenue",
    href: "/earnings",
    icon: "/earnings.svg",
    icon2: "/earnings-2.svg",
  },
  {
    name: "Support & Moderation",
    href: "/support",
    icon: "/bookings.svg",
    icon2: "/bookings-2.svg",
  },
  {
    name: "Marketing & Promotions",
    href: "/promotions",
    icon: "/bookings.svg",
    icon2: "/bookings-2.svg",
  },
  {
    name: "Security & Logs",
    href: "/security",
    icon: "/medal-star.svg",
    icon2: "/medal-star-2.svg",
  },
  {
    name: "Settings",
    href: "/settings",
    icon: "/medal-star.svg",
    icon2: "/medal-star-2.svg",
  },
  
];

export const paymentHistory = [
  {
    id: 1,
    name: "License activation",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "active",
    created_at: "Sep 4, 2021 at 12:14 am",
  },
  {
    id: 2,
    name: "License renewal",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "pending",
    created_at: "Oct 13, 2023 at 08:05 am",
  },
  {
    id: 3,
    name: "Payment for Penalties",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "pending",
    created_at: "Mar 13, 2023 at 08:05 am",
  },
  {
    id: 4,
    name: "License renewal",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "success",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
  {
    id: 5,
    name: "License renewal",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "success",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
  {
    id: 6,
    name: "License renewal",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "success",
    created_at: "Aug 3, 2023 at 12:10 am",
  },
  {
    id: 7,
    name: "License renewal",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "success",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
];

export const packages = [
  {
    id: 1,
    name: "Iphone 13",
    category: "Gadget",
    origin_lga: "Lagos",
    destination_lga: "Rivers",
    status: "delivered",
    created_at: "Sep 4, 2021 at 12:14 am",
  },
  {
    id: 2,
    name: "Iwatch 6",
    category: "Gadget",
    origin_lga: "Lagos",
    destination_lga: "Rivers",
    status: "Registered",
    created_at: "Oct 13, 2023 at 08:05 am",
  },
  {
    id: 3,
    name: "Macbook Pro M1",
    category: "Gadget",
    origin_lga: "Lagos",
    destination_lga: "Rivers",
    status: "delivered",
    created_at: "Mar 13, 2023 at 08:05 am",
  },
  {
    id: 4,
    name: "Airpods 4",
    category: "Gadget",
    origin_lga: "Lagos",
    destination_lga: "Rivers",
    status: "delivered",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
  {
    id: 5,
    name: "Airtel Router",
    category: "Gadget",
    origin_lga: "Lagos",
    destination_lga: "Rivers",
    status: "delivered",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
  {
    id: 6,
    name: "Wired Earpods",
    category: "Gadget",
    origin_lga: "Lagos",
    destination_lga: "Rivers",
    status: "delivered",
    created_at: "Aug 3, 2023 at 12:10 am",
  },
  {
    id: 7,
    name: "Baseus Powerbank",
    category: "Gadget",
    origin_lga: "Lagos",
    destination_lga: "Rivers",
    status: "delivered",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
];
export const riders = [
  {
    id: 1,
    name: "Israel Faizul",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "active",
    created_at: "Sep 4, 2021 at 12:14 am",
  },
  {
    id: 2,
    name: "Daniel Samuel",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "deleted",
    created_at: "Oct 13, 2023 at 08:05 am",
  },
  {
    id: 3,
    name: "Josh Michael",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "active",
    created_at: "Mar 13, 2023 at 08:05 am",
  },
  {
    id: 4,
    name: "Ebubechukwu Agnes",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "unlinked",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
  {
    id: 5,
    name: "Solomon Ideh",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "unlinked",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
  {
    id: 6,
    name: "Adese Samson",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "unlinked",
    created_at: "Aug 3, 2023 at 12:10 am",
  },
  {
    id: 7,
    name: "Hameed Yusuf",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "active",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
];
export const licenses = [
  {
    id: 1,
    name: "License renewal",
    license_type: "International",
    license_duration: "motorcycle",
    status: "active",
    created_at: "Sep 4, 2021 at 12:14 am",
  },
  {
    id: 2,
    name: "License renewal",
    license_type: "International",
    license_duration: "motorcycle",
    status: "declined",
    created_at: "Oct 13, 2023 at 08:05 am",
  },
  {
    id: 3,
    name: "License renewal",
    license_type: "International",
    license_duration: "motorcycle",
    status: "pending",
    created_at: "Mar 13, 2023 at 08:05 am",
  },
  {
    id: 4,
    name: "License renewal",
    license_type: "International",
    license_duration: "motorcycle",
    status: "pending",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
  {
    id: 5,
    name: "License renewal",
    license_type: "International",
    license_duration: "motorcycle",
    status: "pending",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
  {
    id: 6,
    name: "License renewal",
    license_type: "International",
    license_duration: "motorcycle",
    status: "pending",
    created_at: "Aug 3, 2023 at 12:10 am",
  },
  {
    id: 7,
    name: "License renewal",
    license_type: "International",
    license_duration: "motorcycle",
    status: "pending",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
];
